trigger: none

pool:
  name: cong

stages:
- stage: TerraformStage
  displayName: "Terraform Full Workflow"

  jobs:
  - job: TerraformJob
    displayName: "Init Validate Plan Apply"

    steps:

    # 🔹 INIT
    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'conserveci'
        backendAzureRmResourceGroupName: 'conpipe'
        backendAzureRmStorageAccountName: 'const'
        backendAzureRmContainerName: 'connigent'
        backendAzureRmKey: 'Contest'

    # 🔹 VALIDATE
    - task: TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'

    # 🔹 PLAN (save plan)
    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'conserveci'
        commandOptions: '-out=tfplan'

    # 🔹 APPLY (use saved plan)
    - task: TerraformTask@5
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'conserveci'
        commandOptions: 'tfplan -auto-approve'